In [3]:
#自动求导
import torch

x = torch.arange(4.0)#创建一个梯度
x

tensor([0., 1., 2., 3.])

In [4]:
#假设y = x*x ，我们要计算y关于x的梯度，我们需要将这个值保存，所以我们需要为梯度开辟一个空间
#梯度是保存在x中的，设置梯度是在x上设置
x.requires_grad_(True)
x.grad #默认是none

In [5]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [7]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [8]:
#理论上：y对x求导的结果 ： 4* x
x.grad == 4*x

tensor([True, True, True, True])

In [ ]:
#默认情况下，pytorch会累积梯度
#我们需要grad_zero_()清理
#x.grad.zero_()

new_y =  x.sum()
new_y.backward()
x.grad

tensor([1., 1., 1., 1.])